### ISSUE TITLE
remove redphone library

### ISSUE THREAD

**Issue by jaxxstorm** [sensu-plugins/sensu-plugins-pagerduty#10]
It looks to me like redphone won't be supported by @portertech in the near future

https://twitter.com/portertech/status/654188507921956864

I think it's time we moved this plugin to use another library that's actively maintained and is specifically used for pagerduty.

[This](https://github.com/envato/pagerduty) looks like a good candidate

**Comment by analytically** [comment]
I've coded this up but don't have Sensu running with PagerDuty, can you test this for me?

**Comment by analytically** [comment]
Pushed it to the repo, will release after I find time to test.

**Comment by jaxxstorm** [comment]
awesome!

**Comment by jaxxstorm** [comment]
@analytically you need to change the handler class name, I'm getting a superclass mismatch. I can send a PR if you need.

**Comment by analytically** [comment]
Woops, pushed.

**Comment by analytically** [comment]
Were you able to test?

**Comment by jaxxstorm** [comment]
Yes works like a charm!

**Comment by analytically** [comment]
Great, thanks!
