### ISSUE TITLE
Release Cycle

### ISSUE THREAD

**Issue by zbintliff** [sensu-plugins/sensu-plugins-pagerduty#11]
Hey just wondering what the release cycle is like for the new sensu plug in repos? We want to maintain parity with the repo and released gems but will need the the sensu client override before we roll out sense in our org (to replace nagios)

(this is copied from merged PR but not sure if you are notified when comments on closed items)

**Comment by zbintliff** [comment]
bump

**Comment by analytically** [comment]
Hi, I just released 0.0.7. https://rubygems.org/gems/sensu-plugins-pagerduty/versions/0.0.7

**Comment by zbintliff** [comment]
Awesome! Thanks
