### ISSUE TITLE
Your cert has expired

### ISSUE THREAD

**Issue by gstaples** [sensu-plugins/sensu-plugins-pagerduty#18]
[root@sensuserver handlers]# gem cert --add <(curl -Ls https://raw.githubusercontent.com/sensu-plugins/sensu-plugins-pagerduty/master/certs/sensu-plugins.pem)
Added '/CN=mattjones/DC=yieldbot/DC=com'

[root@sensuserver handlers]# gem install sensu-plugins-pagerduty -P LowSecurity
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=mattjones/DC=yieldbot/DC=com not valid after 2016-01-28 21:02:51 UTC

**Comment by eheydrick** [comment]
Thanks for the issue. We are aware of the cert expiration and working on updating it. Apologies for the inconvenience.

**Comment by eheydrick** [comment]
We have removed the cert for now.
