### ISSUE TITLE
Missing config[:json_config]

### ISSUE THREAD

**Issue by shanegibbs** [sensu-plugins/sensu-plugins-pagerduty#2]
@mattyjones where is `config[:json_config]` setup? When using sensu-plugins-pagerduty (0.0.1), I get the following error:

```
bin/handler-pagerduty.rb:34:in `handle': undefined method `[]' for nil:NilClass (NoMethodError)
```

See https://github.com/sensu-plugins/sensu-plugins-pagerduty/pull/1

**Comment by warmfusion** [comment]
Looks like a bug where the script is assuming you've got some additional configuration going on.

Not sure if this'll work, but try adding a 'json_config' section to your pagerduty config like so:

``````
{
  "pagerduty": {
    "api_key": "12345",
    "team_name1": {
      "api_key": "23456"
    },
    "team_name2": {
      "api_key": "34567"
    },
    "json_config": {
      "workaround": "true"
    }
  }
}```
``````

**Comment by shanegibbs** [comment]
I get the same error when using the above config. I also installed version 0.0.2 as well.

**Comment by shanegibbs** [comment]
@warmfusion how about this? https://github.com/sensu-plugins/sensu-plugins-pagerduty/pull/3

**Comment by mattyjones** [comment]
@warmfusion @shanegibbs If this works for you guys I will merge/build/push to rubygems so you can have it.

**Comment by shanegibbs** [comment]
@mattyjones thx. sounds good to me

**Comment by jroyal** [comment]
@mattyjones Was this change ever pushed to rubygems? I don't think it was, but maybe I just messed something up.
