### ISSUE TITLE
Proxy suuport

### ISSUE THREAD

**Issue by gregmark** [sensu-plugins/sensu-plugins-pagerduty#24]
So it doesn't seem that there's any option available to allow this plugin to work behind a firewall. Unless I'm missing something, this is a feature that needs to be added. 

I'm not a ruby programmer, but if you can point me in the right direction, I can probably figure out how to put together a pull request.

Thanks.

--Greg Chavez

**Comment by eheydrick** [comment]
Thanks for the feature request. We're tracking this in #4 so going to close this one.
