### ISSUE TITLE
enable bidirectional functionality

### ISSUE THREAD

**Issue by RiRa12621** [sensu-plugins/sensu-plugins-pagerduty#28]
When working with Pagerduty and Sensu it would be cool to have sensu automatically pull status also from pager duty because you don’t want to look into different places to downtime and ACK and what not.
So we might want to create a downtime if we find that an alert has been ACK’ed in Pagerduty for example

**Comment by majormoses** [comment]
Can you expand on what you want and why? Pagerduty is typically used to aggregate multiple services together in one place for alerting. How would pulling events that originated outside of sensu context such as cloudwatch work?

**Comment by majormoses** [comment]
clsing due to inactivity, feel free to open once you have the time to explain your use case.
