### ISSUE TITLE
Resolution sometimes does not trigger pagerduty

### ISSUE THREAD

**Issue by danktec** [sensu-plugins/sensu-plugins-pagerduty#31]
I've seen this occur a number of times where there are bulk (10 or more at a time) incidents triggered, when they are resolved in sensu they are not resolved at PD.

Could be a network issue, perhaps a bulk request problem... maybe even an API bug or limitation at PD... But i thought i'd ask here, if others have seen this happen on their own infrastructure.

I have not started debugging and have not re-created the issue. Just noticed it a number of times when we have a large outage, and intermittently at other times.  v0.23.3

**Comment by majormoses** [comment]
I have seen this occasionally but have not had the time to attempt to reproduce it. Maybe this will help? #39  @eheydrick can we get a release so we can test?

**Comment by eheydrick** [comment]
Working on getting a release out.

**Comment by eheydrick** [comment]
Just released 2.2.0.

**Comment by eheydrick** [comment]
@dhdanno can you see if 2.2.0 helps.

**Comment by majormoses** [comment]
Due to lack of feedback and I have not seen this in a while I am going to close this out. If someone has issues please comment back and we will re-open.
