### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by guru-beach** [sensu-plugins/sensu-plugins-pagerduty#32]
It'd be helpful to know you can add pager_team to checks and not just at the client level.  I had to dig into the code to get my pages to route properly on a per-metric basis.  I also feel this is a much easier solution to implement than pd_override, especially when defining in something like puppet.

At first I had client level pd_override settings on a per metric basis (and also in dedup) and that didn't work properly.   Adding pager_team to the check worked however.

**Comment by ghost** [comment]
@guru-beach, can you give me an example of each. I'm trying to set the pager_team in my checks and I'm getting the following error:

`{"timestamp":"2016-09-19T17:29:46.316569-0400","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/pagerduty.rb","name":"pagerduty"},"output":["/etc/sensu/handlers/pagerduty.rb:53:in`api_key': undefined method `[]' for nil:NilClass (NoMethodError)\n","\tfrom /etc/sensu/handlers/pagerduty.rb:87:in`block in handle'\n","\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'\n","\tfrom /opt/sensu/embedded/lib/ruby/2.0.0/timeout.rb:97:in`timeout'\n","\tfrom /etc/sensu/handlers/pagerduty.rb:79:in `handle'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:55:in`block in class:Handler'\n"]}
`

My cron.json check looks like this

``` json
{
"checks":{
"procs-cron":{
    "command": "/etc/sensu/plugins/check-procs.rb -p crond -W 1", 
    "handlers": [
        "default", 
        "mailer", 
        "pagerduty"
    ], 
    "interval": 60, 
    "pager_team": [
        "ops", 
        "deliverability"
    ], 
    "subscribers": [
        "all"
    ]
}
}
}
```

**Comment by guru-beach** [comment]
pager_team isn't a list item, it's a string.

```
{
  "checks": {
    "singtel_broadband_record_linkage_amg_match_count": {
      "enable_deprecated_filtering": false,
      "command": "/opt/sensu/embedded/bin/check-graphite.rb -h localhost:8000 -p 1week -x -t nj.bank.SingtelBroadbandRecordLinkage.match_count -l 100.0",
      "handlers": [
        "pagerduty"
      ],
      "interval": 60,
      "pager_team": "data_dmp",
      "standalone": true
    }
  }
}
```

**Comment by ghost** [comment]
I can only provide one pager_team? What if I want to page more than one team based on the alert?

`"pager_team": "ops, sre"`

**Comment by majormoses** [comment]
@henrysail lets keep that conversation here: https://github.com/sensu-plugins/sensu-plugins-pagerduty/issues/17 and leave this about documentation update. I can make a pr for this when I get some time and my other current open pr is merged.

**Comment by majormoses** [comment]
@guru-beach yup we use it the same way, I will update doc when I can with how we use/configure it.

**Comment by majormoses** [comment]
@guru-beach please check out the documentation enhancement in #44 and let me know if there is anything more we should add or explain.

**Comment by majormoses** [comment]
closing as documentation enhancement was made and no feedback was given, feel free to re-open if it is still lacking.
