### ISSUE TITLE
Doesn't create incidents when "flapping"

### ISSUE THREAD

**Issue by sara4dev** [sensu-plugins/sensu-plugins-pagerduty#33]
Sensu can generate events with action `flapping`, and the handler should be able to create incident when events are flapping.

**Comment by majormoses** [comment]
@saravanakumar-periyasamy You need to update your handler config to change the default behavior of: handle_flapping to true. See here for more info: https://sensuapp.org/docs/0.24/reference/handlers.html#handler-configuration

**Comment by majormoses** [comment]
just took a look at the code and it does require a minor tweak, I can open a PR for it if you want to do some testing.

**Comment by majormoses** [comment]
@saravanakumar-periyasamy can you test my change and validate that this combined with the required config change works?

**Comment by sara4dev** [comment]
@majormoses - code does look good! I have the same change in my code & running for months now. My bad, I did not give the PR for that. Thanks for fixing it!

**Comment by majormoses** [comment]
@saravanakumar-periyasamy no worries, can you comment on the PR saying you have tested it? This will help it typically get merged faster.

**Comment by sara4dev** [comment]
tested this code & fixes the issue! Infact I am running this code fix in prod for several months now.

**Comment by majormoses** [comment]
I meant on the actual PR: https://github.com/sensu-plugins/sensu-plugins-pagerduty/pull/41 as you had already commented here.
