### ISSUE TITLE
Please release new gem with contexts support!

### ISSUE THREAD

**Issue by spang** [sensu-plugins/sensu-plugins-pagerduty#35]
hey there,

The new support for contexts is awesome. Thanks @zroger! I was wondering if you'd consider bumping the version and uploading a new gem with this version. As it is, it is not very easy to install a version of this plugin with support for contexts.

**Comment by johntdyer** [comment]
@zroger  / @sstarcher - Can you guys please cut a new release ?

**Comment by zroger** [comment]
Wish I could help, but I'm not the gem/repo maintainer.

**Comment by eheydrick** [comment]
I just released 2.1.0 which has contexts support.
