### ISSUE TITLE
pager_team variable with array of teams in check-definition

### ISSUE THREAD

**Issue by garep** [sensu-plugins/sensu-plugins-pagerduty#37]
I am specifying the following in my check-definition in sensu:
```
      "interval": 30,
      "handle": true,
      "occurrences": 5,
      "refresh": 500,
      "pager_team": [
        "devtools_sensu",
        "devcloud_support_sensu"
      ],
      "notification": "Github predix dev2 snmp used storage percent"
    }
  }
}
```

Is pager_team per check a 1:1 or can we specify multiple pager_teams per above?  It seems to only be alerting the first team specified (devtools_sensu).  

Thanks,
Gary

**Comment by majormoses** [comment]
Yes it is intended to be a 1:1 relation, if you want to alert multiple teams then you should create the service and escalation policy like this: https://support.pagerduty.com/hc/en-us/articles/202828970-Notify-Multiple-Users-at-Once though I tend to discourage such setups as this can create confusion on who is supposed to be the incident commander.

**Comment by majormoses** [comment]
If you need any further clarification or advice feel free ping me to re-open.
