### ISSUE TITLE
Consider re-ordering setting overrides for client/check/json_config

### ISSUE THREAD

**Issue by guru-beach** [sensu-plugins/sensu-plugins-pagerduty#42]
Currently a client level pager_team overrides all check based pager_team setting. 

However, it would make more sense (to me at least) to have check level settings override client level settings.   This allows the client level setting to be the "default" for all checks, but allows various checks to be able to define teams.   This comes in especially handy when we have applications doing checking and routing to their responsible teams where system level checks will typically go to our system engineering team.

**Comment by majormoses** [comment]
https://github.com/sensu-plugins/sensu-plugins-pagerduty/pull/43

**Comment by majormoses** [comment]
closed per #43
