### ISSUE TITLE
Pagerduty handler is not honororing "occurrences" property of checks, and is additionally being triggered when checks are silenced.

### ISSUE THREAD

**Issue by zenmetsu** [sensu-plugins/sensu-plugins-pagerduty#51]
We have the pagerduty handler set up in parallel with our email handler. We notice that on checks where `"occurrences" : 5` is being set, email notifications are properly suppressed until the 5th occurrence, however a pagerduty incident is created immediately upon the first failed check.

Additionally, when silencing hosts within uchiwa in anticipation of a maintenance window, email handler properly suppresses notification during the maintenance window, however pagerduty handler begins spamming the operations team despite checks being silenced within the dashboard.

**Comment by zenmetsu** [comment]
We have the pagerduty handler set up in parallel with our email handler.  We notice that on checks where '"occurrences" : 5'   is being set, email notifications are properly suppressed until the 5th occurrence, however a pagerduty incident is created immediately upon the first failed check.

Additionally, when silencing hosts within uchiwa in anticipation of a maintenance window, email handler properly suppresses notification during the maintenance window, however pagerduty handler begins spamming the operations team despite checks being silenced within the dashboard.

**Comment by zenmetsu** [comment]
Currently using 
Sensu 1.4.3 
Uchiwa 0.10.3

**Comment by zenmetsu** [comment]
closing issue, found workaround by adding filters to handle the occurrences issue, and realized that the stash-based silencing of the version of uchiwa that was running was not going to work as expected.  verified that using silence API that handler was indeed suppressed.

**Comment by majormoses** [comment]
@zenmetsu yes that was a breaking change that was called out in the changelog and versioned as a major. If you are not pinning your gems I strongly recommend you read https://github.com/sensu-plugins/community/blob/master/best_practices/production_deployments/plugins/PINNING_VERSIONS.md and take steps to make sure you don't intentionally pull in breaking changes without human intervention.

**Comment by majormoses** [comment]
> Uchiwa 0.10.3

That's pretty ancient from what I recall, ya there were some changes around stash/silence the latest version of the plugin should work with the latest version of sensu + uchiwa.

**Comment by zenmetsu** [comment]
Yes, I had deployed a container which had an old version of Uchiwa.  I've since rolled my own container with Uchiwa 1.2.0 and everything is good.  This wasn't an issue with pinning, we were adding PagerDuty integration to an existing deployment and ran into the quirks, but thanks for the helpful and prompt response.
