### ISSUE TITLE
add retry support

### ISSUE THREAD

**Issue by jaxxstorm** [sensu-plugins/sensu-plugins-pagerduty#6]
There's times when the PD API just doesn't do what it's meant to, for whatever reasons. Perhaps your network is screwed, who knows?

Anyway, I think this handler should have the option to retry creating and resolving an incident X number of times. Perhaps we should put it in the JSON config?

**Comment by mattyjones** [comment]
@jaxxstorm  Thats a good thought! Do you have tim to code something up and I will merge it through?
